version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    depends_on:
      - db  # Ensure DB is started before the web service
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: appdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]  # Test the web service on the expected port
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./app:/var/www/html  # Mount the local app directory to the container

  db:
    image: mysql:8.0  # Use the MySQL 8.0 image
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data in a named volume
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "ping"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_data:  # Named volume for persistent data storage
