version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:80"  # ✅ Map host port 9000 to container port 80
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-prootpass", "ping"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_data:
